import type {
  FeedbackItem,
  ProgramInitiative,
  ProgramPillarId,
  ResultMetric,
  VoiceReport,
} from "./types";

export const pillars: Array<{
  id: ProgramPillarId;
  no: string;
  title: string;
  description: string;
}> = [
  {
    id: "research",
    no: "1",
    title: "Танилцах, дүн шинжилгээ, судалгаа, хөгжүүлэлт",
    description: "Ажлын байр, процесс, бодит хэрэгцээг судалж сайжруулалтын санал боловсруулах.",
  },
  {
    id: "productivity",
    no: "2",
    title: "Бүтээмжийг дээшлүүлэх, эрсдэлийг бууруулах",
    description: "Давтамжтай алдаа, хоцролт, эрсдэлийг багасгах туршилт болон арга хэмжээ.",
  },
  {
    id: "digital-learning",
    no: "3",
    title: "Цахим шилжилт, сургалт, зөвлөгөө",
    description: "Ажилтанд ойлгомжтой цахим хэрэгсэл, сургалт, зөвлөгөөний багц.",
  },
];

export const initiatives: ProgramInitiative[] = [
  {
    id: "rd-001",
    pillarId: "research",
    no: 1,
    title: "Ажилтны дуу хоолойн судалгааны маягт, асуулга боловсруулах",
    owner: "Судалгаа хөгжүүлэлт",
    department: "ДХШ",
    score: 82,
    target: 100,
    status: "in_progress",
    year: 2026,
    start_date: "2026-01-06",
    end_date: "2026-06-30",
    quarters: { q1: "done", q2: "done", q3: "none", q4: "none" },
  },
  {
    id: "rd-002",
    pillarId: "research",
    no: 2,
    title: "Журам, процессын давхардал ба сул цэгийн зураглал гаргах",
    owner: "Дотоод хяналт",
    department: "Бодлого",
    score: 76,
    target: 100,
    status: "in_progress",
    year: 2026,
    start_date: "2026-04-01",
    end_date: "2026-09-30",
    quarters: { q1: "none", q2: "done", q3: "planned", q4: "none" },
  },
  {
    id: "rd-003",
    pillarId: "productivity",
    no: 3,
    title: "Эрсдэлийн бүртгэл, corrective action үр дүнгийн dashboard нэгтгэх",
    owner: "Эрсдэлийн удирдлага",
    department: "ДХШ",
    score: 64,
    target: 100,
    status: "planned",
    year: 2026,
    start_date: "2026-07-01",
    end_date: "2026-12-15",
    quarters: { q1: "none", q2: "none", q3: "planned", q4: "planned" },
  },
  {
    id: "rd-004",
    pillarId: "productivity",
    no: 4,
    title: "ХШ болон журмын биелэлтийн тайлан шинжилгээний загвар гаргах",
    owner: "Тайлан шинжилгээ",
    department: "ДХШ",
    score: 58,
    target: 100,
    status: "planned",
    year: 2026,
    start_date: "2026-04-15",
    end_date: "2026-12-20",
    quarters: { q1: "none", q2: "planned", q3: "planned", q4: "planned" },
  },
  {
    id: "rd-005",
    pillarId: "digital-learning",
    no: 5,
    title: "AI туслахын мэдлэгийн сан, зөвлөмжийн эхний хувилбар",
    owner: "AI туслах",
    department: "Хөгжүүлэлт",
    score: 71,
    target: 100,
    status: "in_progress",
    year: 2026,
    start_date: "2026-01-15",
    end_date: "2026-09-01",
    quarters: { q1: "done", q2: "done", q3: "planned", q4: "none" },
  },
  {
    id: "rd-006",
    pillarId: "digital-learning",
    no: 6,
    title: "Ажилтны сургалт, тохиргоо, удирдлагын төвийн шаардлага боловсруулах",
    owner: "Удирдлагын төв",
    department: "Хөгжүүлэлт",
    score: 49,
    target: 100,
    status: "delayed",
    year: 2026,
    start_date: "2026-07-01",
    end_date: "2026-12-31",
    quarters: { q1: "none", q2: "none", q3: "planned", q4: "planned" },
  },
];

export const resultMetrics: ResultMetric[] = [
  {
    id: "metric-voice",
    pillarId: "research",
    label: "Ажилтны дуу хоолой",
    target: "120 санал",
    actual: "86 санал",
    owner: "Судалгаа хөгжүүлэлт",
    progress: 72,
  },
  {
    id: "metric-risk",
    pillarId: "productivity",
    label: "Эрсдэлийн бууралт",
    target: "20%",
    actual: "11%",
    owner: "Эрсдэлийн удирдлага",
    progress: 55,
  },
  {
    id: "metric-analysis",
    pillarId: "productivity",
    label: "Тайлан шинжилгээ",
    target: "8 dashboard",
    actual: "5 dashboard",
    owner: "Тайлан шинжилгээ",
    progress: 63,
  },
  {
    id: "metric-ai",
    pillarId: "digital-learning",
    label: "AI туслах",
    target: "30 workflow",
    actual: "18 workflow",
    owner: "Хөгжүүлэлт",
    progress: 60,
  },
];

export const voiceReports: VoiceReport[] = [
  {
    id: "voice-001",
    pillarId: "research",
    no: 1,
    title: "Ажилтны санал, асуулгын нэгдсэн тайлан",
    participants: 42,
    responsible: "ДХШ",
    submittedAt: "2026-08-11",
    status: "completed",
  },
  {
    id: "voice-002",
    pillarId: "digital-learning",
    no: 2,
    title: "Сургалт, зөвлөгөөний хэрэгцээний судалгаа",
    participants: 31,
    responsible: "Хөгжүүлэлт",
    submittedAt: "2026-08-15",
    status: "in_progress",
  },
];

export const feedbackItems: FeedbackItem[] = [
  {
    id: "fb-questions",
    type: "question",
    title: "Санал, асуулга",
    department: "Нийт",
    count: 54,
    status: "in_progress",
  },
  {
    id: "fb-suggestions",
    type: "suggestion",
    title: "Тунгаалт, дүгнэлт",
    department: "ДХШ",
    count: 18,
    status: "planned",
  },
  {
    id: "fb-participation",
    type: "participation",
    title: "Оролцоо",
    department: "Хөгжүүлэлт",
    count: 73,
    status: "completed",
  },
];
